insert into user_tb(username, password, email,pic_url) values('ssar', '1234', 'ssar@nate.com','basic.png');
insert into user_tb(username, password, email,pic_url) values('cos', '1234', 'cos@nate.com','basic.png');
insert into user_tb(username, password, email,pic_url) values('sin', '1234', 'sin@nate.com','basic.png');
insert into board_tb(title, content, user_id, created_at) values('제목1', '내용1', 1, now());
insert into board_tb(title, content, user_id, created_at) values('제목2', '내용2', 1, now());
insert into board_tb(title, content, user_id, created_at) values('제목3', '내용3', 1, now());
insert into board_tb(title, content, user_id, created_at) values('제목4', '내용4', 2, now());
insert into board_tb(title, content, user_id, created_at) values('제목5', '내용5', 2, now());
insert into board_tb(title, content, user_id, created_at) values('가', '내용5', 2, now());
insert into board_tb(title, content, user_id, created_at) values('가가가', '내용5', 2, now());
insert into board_tb(title, content, user_id, created_at) values('나나나', '내용5', 2, now());
insert into board_tb(title, content, user_id, created_at) values('나나나', '내용5', 2, now());
insert into board_tb(title, content, user_id, created_at) values('나나나', '내용5', 2, now());
insert into board_tb(title, content, user_id, created_at) values('나나나', '내용5', 2, now());
insert into board_tb(title, content, user_id, created_at) values('나나5', '내용5', 2, now());
insert into board_tb(title, content, user_id, created_at) values('제목5', '내용5', 2, now());
insert into board_tb(title, content, user_id, created_at) values('제목5', '내용5', 2, now());
insert into reply_tb(comment, board_id, user_id) values('댓글1', 5, 1);
insert into reply_tb(comment, board_id, user_id) values('댓글2', 2, 2);
insert into reply_tb(comment, board_id, user_id) values('댓글3', 3, 2);
insert into reply_tb(comment, board_id, user_id) values('댓글4', 5, 1);
insert into reply_tb(comment, board_id, user_id) values('댓글5', 5, 1);
insert into reply_tb(comment, board_id, user_id) values('댓글6', 5, 1);
insert into reply_tb(comment, board_id, user_id) values('댓글6', 5, 1);
insert into reply_tb(comment, board_id, user_id) values('댓글6', 12, 2);
insert into reply_tb(comment, board_id, user_id) values('댓글6', 12, 3);
insert into reply_tb(comment, board_id, user_id) values('댓글6', 12, 1);
insert into reply_tb(comment, board_id, user_id) values('댓글6', 12, 1);
